seed: 1996

### -------  DATASET SETTINGS --------------

dataset_name: "generation_sample"
data: "./datasets/sample/generation_small.txt"
normalize: 2

### -------  DEVICE SETTINGS --------------

device: "cuda:1"
use_gpu: True
gpu: 0

### -------  I/O LENGTH SETTINGS --------------

window_size: 192 # window_size % 2^levels == 0
horizon: 3
concat_len: 165
single_step: 0
single_step_output_One: 0
lastWeight: 0.5

### -------  TRAINING SETTINGS --------------
train: True
resume: False
evaluate: False
log_interval: 2000
save: "model/model.pt"
optim: "adam"
L1Loss: True
num_nodes: 8
batch_size: 8
lr: 5e-3
weight_decay: 0.00001
epochs: 2
lradj: 1
save_path: "exp/sample_checkpoints/"
model_name: "generation_small"

### -------  MODEL SETTINGS --------------
hidden_size: 1.0
INN: 1
kernel: 5
dilation: 1
positionalEcoding: False
dropout: 0.5
groups: 1
levels: 3
num_decoder_layer: 1
stacks: 2
long_term_forecast: False # if True -> in code concat_len = window_size - horizon
RIN: False
decompose: False
